apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: mario
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - host: ilove.k8s.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-spring
                port:
                  number: 80
          - path: /mario
            pathType: Prefix
            backend:
              service:
                name: svc-mario
                port:
                  number: 80
          - path: /tem
            pathType: Prefix
            backend:
              service:
                name: svc-tem
                port:
                  number: 80
